import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });
import styles from "../styles/Home.module.scss";

export default function Home() {
  return (
    <>
      <Head>
        <title>B&B with Nextjs</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className={styles.Hero}>
          <img
            className={styles.img1}
            src="https://cdn.pixabay.com/photo/2016/06/24/10/47/house-1477041_640.jpg"
          />
          <p>
            Lorem ipsum dolor sit, amet consectetur adipisicing elit.
            Repudiandae fugit veritatis quibusdam tenetur ipsam corporis
            eligendi accusamus possimus non nulla dolore aliquam asperiores
            culpa officiis ipsum, qui rerum blanditiis fugiat.
          </p>
        </div>
        <div className={styles.body}>
          <img
            className={styles.img2}
            src="https://dhqbz5vfue3y3.cloudfront.net/fotomondobb/2025_top.jpg"
          />
          <p>
            Lorem ipsum dolor sit, amet consectetur adipisicing elit.
            Repudiandae fugit veritatis quibusdam tenetur ipsam corporis
          </p>
          <img
            className={styles.img2}
            src="https://www.cantodegliaranci.it/wp-content/uploads/2020/10/sala-colazione.jpg"
          />
        </div>
      </main>
    </>
  );
}
